'use client'


import { Provider } from "react-redux";
import { PersistGate } from 'redux-persist/integration/react';
import { store, persistor } from "./redux/Store/store";

//import type { Metadata } from "next";
import '@fontsource-variable/onest';
import "./globals.css";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="font-variable-onest">
       <PersistGate loading={null} persistor={persistor}>
       <Provider store={store}>
        {children}
      </Provider>
      </PersistGate>
      </body>
    </html>
  );
}
